#!/bin/bash

set -e

echo "Building using architecture: ${ARCHS}"

GLASSTUAL_PRODUCT_LOCATION="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
GLASSTUAL_PRODUCT_BINARY="${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}"

services=(
	'Historic Log File Manager'
	'Inline Content Loader'
	'IRC Remote Connection Manager'
)

for service in "${services[@]}"; do
	cd "${GLASSTUAL_WORKSPACE_DIR}/XPC Services/${service}/"

	xcodebuild -target "$service" \
		-configuration "${GLASSTUAL_XPC_SERVICE_BUILD_SCHEME}" \
		ARCHS="${ARCHS}" \
		CODE_SIGNING_ALLOWED="${CODE_SIGNING_ALLOWED}" \
		CODE_SIGNING_REQUIRED="${CODE_SIGNING_REQUIRED}" \
		CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
		CODE_SIGN_STYLE="${CODE_SIGN_STYLE}" \
		DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
		GLASSTUAL_IRC_PROVISIONING_PROFILE="${GLASSTUAL_IRC_PROVISIONING_PROFILE}" \
		GLASSTUAL_SCROLLBACK_PROVISIONING_PROFILE="${GLASSTUAL_SCROLLBACK_PROVISIONING_PROFILE}" \
		GLASSTUAL_INLINE_CONTENT_PROVISIONING_PROFILE="${GLASSTUAL_INLINE_CONTENT_PROVISIONING_PROFILE}" \
		GLASSTUAL_CORE_MEDIA_PROVISIONING_PROFILE="${GLASSTUAL_CORE_MEDIA_PROVISIONING_PROFILE}" \
		GLASSTUAL_WORKSPACE_DIR="${GLASSTUAL_WORKSPACE_DIR}" \
		GLASSTUAL_PRODUCT_LOCATION="${GLASSTUAL_PRODUCT_LOCATION}" \
		GLASSTUAL_PRODUCT_BINARY="${GLASSTUAL_PRODUCT_BINARY}"
done
