#!/bin/bash

# Writes BuildConfig.h from build settings.
#
# Runs as the only build phase of the "BuildConfig" aggregate target in
# Glasstual.xcodeproj. Every target that includes the header depends on
# that target and has GLASSTUAL_BUILD_HEADERS_DIR on its header search path.
# The file is only rewritten when its content changes so dependents are not
# rebuilt needlessly. Feature flags are not written here; they reach the
# compilers through GCC_PREPROCESSOR_DEFINITIONS and
# SWIFT_ACTIVE_COMPILATION_CONDITIONS (see Configurations/Base.xcconfig).

set -euo pipefail

: "${GLASSTUAL_BUILD_HEADERS_DIR:?must be set by Xcode (see Configurations/Base.xcconfig)}"

mkdir -p "${GLASSTUAL_BUILD_HEADERS_DIR}"

# Scratch files go to the per-target temp dir: the user-script sandbox only
# allows writes to declared outputs and to TEMP_DIR.
scratch_dir="${TEMP_DIR:-${TMPDIR:-/tmp}}"

replace_if_changed() {
	local candidate="$1"
	local destination="$2"

	if cmp -s "${candidate}" "${destination}"; then
		rm -f "${candidate}"
	else
		mv -f "${candidate}" "${destination}"
		echo "Wrote ${destination}"
	fi
}

header_banner="/* Generated by Scripts/GenerateBuildConfig.sh. Do not edit; changes are not saved or committed. */"

# ---- BuildConfig.h --------------------------------------------------------

build_config="${GLASSTUAL_BUILD_HEADERS_DIR}/BuildConfig.h"
build_config_tmp="${scratch_dir}/BuildConfig.h.tmp"

{
	echo "${header_banner}"
	echo
	echo "#define TXBundleBuildProductName                  @\"${GLASSTUAL_PRODUCT_NAME}\""
	echo "#define TXBundleBuildProductIdentifier            @\"${GLASSTUAL_BUNDLE_IDENTIFIER}\""
	echo "#define TXBundleBuildProductIdentifierCString      \"${GLASSTUAL_BUNDLE_IDENTIFIER}\""
	echo "#define TXBundleBuildGroupContainerIdentifier     @\"${GLASSTUAL_GROUP_CONTAINER_IDENTIFIER}\""
	echo "#define TXBundleBuildVersion                      @\"${CURRENT_PROJECT_VERSION}\""
	echo "#define TXBundleBuildVersionShort                 @\"${MARKETING_VERSION}\""
} > "${build_config_tmp}"

replace_if_changed "${build_config_tmp}" "${build_config}"
