#!/bin/bash

# Writes BuildConfig.h and FeatureFlags.h from build settings.
#
# Runs as the only build phase of the "BuildConfig" aggregate target in
# Glasstual.xcodeproj. Every target that includes either header depends on
# that target and has GLASSTUAL_BUILD_HEADERS_DIR on its header search path.
# Files are only rewritten when their content changes so dependents are not
# rebuilt needlessly.

set -euo pipefail

: "${GLASSTUAL_BUILD_HEADERS_DIR:?must be set by Xcode (see Configurations/Base.xcconfig)}"

mkdir -p "${GLASSTUAL_BUILD_HEADERS_DIR}"

# Scratch files go to the per-target temp dir: the user-script sandbox only
# allows writes to declared outputs and to TEMP_DIR.
scratch_dir="${TEMP_DIR:-${TMPDIR:-/tmp}}"

replace_if_changed() {
	local candidate="$1"
	local destination="$2"

	if cmp -s "${candidate}" "${destination}"; then
		rm -f "${candidate}"
	else
		mv -f "${candidate}" "${destination}"
		echo "Wrote ${destination}"
	fi
}

header_banner="/* Generated by Scripts/GenerateBuildConfig.sh. Do not edit; changes are not saved or committed. */"

# ---- BuildConfig.h --------------------------------------------------------

build_config="${GLASSTUAL_BUILD_HEADERS_DIR}/BuildConfig.h"
build_config_tmp="${scratch_dir}/BuildConfig.h.tmp"

{
	echo "${header_banner}"
	echo
	echo "#define TXBundleBuildProductName                  @\"${GLASSTUAL_PRODUCT_NAME}\""
	echo "#define TXBundleBuildProductIdentifier            @\"${GLASSTUAL_BUNDLE_IDENTIFIER}\""
	echo "#define TXBundleBuildProductIdentifierCString      \"${GLASSTUAL_BUNDLE_IDENTIFIER}\""
	echo "#define TXBundleBuildGroupContainerIdentifier     @\"${GLASSTUAL_GROUP_CONTAINER_IDENTIFIER}\""
	echo "#define TXBundleBuildVersion                      @\"${CURRENT_PROJECT_VERSION}\""
	echo "#define TXBundleBuildVersionShort                 @\"${MARKETING_VERSION}\""
	echo "#define TXBundleBuildScheme                       @\"${GLASSTUAL_BUILD_SCHEME_TOKEN}\""

	if [ -z "${CODE_SIGN_IDENTITY:-}" ] || [ "${CODE_SIGNING_ALLOWED:-YES}" = "NO" ]; then
		echo "#define TXBundleBuiltWithoutCodeSigning           1"
	fi
} > "${build_config_tmp}"

replace_if_changed "${build_config_tmp}" "${build_config}"

# ---- FeatureFlags.h -------------------------------------------------------
#
# The same flags are passed on the compiler command line through
# GCC_PREPROCESSOR_DEFINITIONS. The header only provides defaults for
# translation units that are compiled without them.

feature_flags="${GLASSTUAL_BUILD_HEADERS_DIR}/FeatureFlags.h"
feature_flags_tmp="${scratch_dir}/FeatureFlags.h.tmp"

feature_names=(
	GLASSTUAL_BUILT_INSIDE_SANDBOX
	GLASSTUAL_BUILT_WITH_SPARKLE_ENABLED
	GLASSTUAL_BUILT_WITH_ADVANCED_ENCRYPTION
	GLASSTUAL_BUILT_AS_UNIVERSAL_BINARY
)

{
	echo "${header_banner}"
	echo

	for feature in "${feature_names[@]}"; do
		value="${!feature:-0}"

		echo "#ifndef ${feature}"
		echo "#define ${feature} ${value}"
		echo "#endif"
		echo
	done
} > "${feature_flags_tmp}"

replace_if_changed "${feature_flags_tmp}" "${feature_flags}"
