#!/bin/bash

# Writes Configurations/Version.generated.xcconfig (gitignored) so that
# CURRENT_PROJECT_VERSION, and therefore CFBundleVersion, is derived from the
# date of the last git commit (format yymmdd.HH, UTC).
#
# Runs as the pre-action of the Glasstual scheme's Build action and may be
# run by hand or from CI before invoking xcodebuild. Without it builds fall
# back to CURRENT_PROJECT_VERSION = 0 from Configurations/Base.xcconfig.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"

output="${repo_root}/Configurations/Version.generated.xcconfig"

bundle_version="0"

if command -v git > /dev/null 2>&1 && git -C "${repo_root}" rev-parse --git-dir > /dev/null 2>&1; then
	commit_date="$(git -C "${repo_root}" log -n1 --format='%at' 2> /dev/null || true)"

	if [ -n "${commit_date}" ]; then
		bundle_version="$(/bin/date -u -r "${commit_date}" '+%y%m%d.%H')"
	fi
fi

candidate="${output}.tmp"

{
	echo "// Generated by Scripts/UpdateVersion.sh. Do not edit or commit."
	echo "CURRENT_PROJECT_VERSION = ${bundle_version}"
} > "${candidate}"

if cmp -s "${candidate}" "${output}"; then
	rm -f "${candidate}"
	echo "Version unchanged: ${bundle_version}"
else
	mv -f "${candidate}" "${output}"
	echo "Version written: ${bundle_version}"
fi
